### PR TITLE
Check type of data, return proper type

### PR DESCRIPTION
**Pull request by benoitchantre**
Fix issue #1

### CODE REVIEW

**Comment by AdamQuadmon** [comment]
I've added some comments to the fix. Please add tests too if you can :P
Thanks for contributing.

**Comment by benoitchantre** [comment]
What is the difference between the _fixtures_ directory and the _expected_ directory?

**Comment by AdamQuadmon** [comment]
Tests reads `fixtures` files and assert the output (in `tmp` folder) equals files in `expected` folder. 
This is my first grunt task, if you think there is a better way to do that feel free to change it!

**Comment by benoitchantre** [comment]
I have no advice to give you, I have not written any grunt task yet.
_Mocha_ and _Jasmine_ are popular test frameworks but maybe there's no need to change the one you used.
Could you add the test yourself? I don't have the time to write them before next week.

**Comment by AdamQuadmon** [comment]
ok, don't worry, I use jasmine for my main project but nodeunit came as default when you create a grunt task with `grunt-init gruntplugin` so I choose to not change this.

I'll take care of tests.

**Comment by benoitchantre** [comment]
Thanks

**Comment by AdamQuadmon** [comment]
Thank you for this!

**Comment by benoitchantre** [comment]
Any idea when you will release it?

**Comment by AdamQuadmon** [comment]
done

**Comment by benoitchantre** [comment]
I mean when you will bump the version of _package.json_.
At the moment we can't get this improvement with npm.

**Comment by AdamQuadmon** [comment]
I've just updated it and published, did you checked it?

**Comment by benoitchantre** [comment]
It works. Maybe I have tried to early.
Thanks.

**Pull request merged**
